apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "0" }
spec:
  project: kubevista
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 3.5.0
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: kubevista-dev
        region: us-west-2
        vpcTags:
          Name: kubevista-dev-vpc
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
        replicaCount: 2
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 5
        resources:
          requests: { cpu: 100m, memory: 128Mi }
          limits: { cpu: 500m, memory: 512Mi }
  destination: { server: https://kubernetes.default.svc, namespace: kube-system }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ServerSideApply=true]
    retry: { limit: 5 }
