apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example-application-secret
  namespace: kubevista
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: example-application-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: kubevista/example
        property: api-key
