{{ if .Values.nodeOperator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevista-node-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-node-operator
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-node-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-node-operator
subjects:
  - kind: ServiceAccount
    name: kubevista-node-operator
    namespace: {{ .Release.Namespace }}
{{ end }}
