import type {Resident} from './station'
export type Facility='control'|'services'|'telemetry'
export const equipment={control:['API server','Scheduler','Controllers','etcd'],services:['Service','EndpointSlice','Pod backend'],telemetry:['Prometheus','Grafana','Alertmanager','Loki','Tempo','OTel gateway','OTel agent']}
export function namespaceColor(name:string){
 const palette:Record<string,string>={argocd:'#8dd3c7',kubevista:'#9fc7e7','kubevista-lab':'#e4ba8a',observability:'#b6abdf','kube-system':'#c3ce88',default:'#e0a9ba'}
 if(palette[name])return palette[name]
 let hash=0;for(const c of name)hash=(hash*31+c.charCodeAt(0))>>>0
 return `hsl(${hash%360} 48% 74%)`
}
const configuredPaths=[['Node logs','OTel agent','Loki'],['Host / kubelet metrics','OTel agent','OTel gateway','Prometheus exporter :8889','Prometheus'],['App traces','OTel gateway','Tempo'],['App logs','OTel gateway','Loki']]
export function TopologyPanel({facility,residents,simulated,onClose,onHighlight}:{facility:Facility;residents:Resident[];simulated:boolean;onClose:()=>void;onHighlight:(name:string)=>void}){
 const services=[...new Set(residents.flatMap(p=>p.services))].sort()
 return <aside className="topology-panel" aria-label={`${facility} topology`}><header><h2>{facility==='control'?'Control plane':facility==='services'?'Service connections':'Telemetry pipeline'}</h2><button aria-label="Close topology" onClick={onClose}>×</button></header>
 {facility==='control'?<><p className="topology-source">EKS architecture · managed internals, not discovered static pods</p><div className="topology-parts">{equipment.control.map((name,i)=><article key={name}><strong>{name}</strong><p>{['Accepts Kubernetes API requests. Only the aggregate /readyz probe is measured.','Assigns unscheduled pods to eligible worker nodes.','Reconciles desired and observed state.','Persists Kubernetes cluster state.'][i]}</p><small>{i===0?'Probe shown on room':'Internal health unknown'}</small></article>)}</div><details><summary>Configured AWS boundaries</summary><p>Terraform defines public, private worker, and intra control-plane interface subnets across three AZs. The managed control-plane hosts are AWS-owned. Live node → subnet mapping is not available; no worker placement is inferred.</p></details></>:facility==='telemetry'?<><p className="topology-source">Configured in Argo CD manifests · arrows are not measured traffic</p>{configuredPaths.map(path=><div className="topology-path" key={path.join('/')} aria-label={path.join(' to ')}>{path.map((name,i)=><span key={i}>{i>0&&<b aria-hidden="true">→</b>}<button onClick={()=>onHighlight(name)}>{name}</button></span>)}</div>)}<div className="topology-parts">{equipment.telemetry.map(name=>{const needle=name.toLowerCase().replace('otel ','otel-');const pods=residents.filter(p=>p.workload.name.toLowerCase().includes(needle));return <button key={name} onClick={()=>onHighlight(name)}><strong>{name}</strong><small>{pods.length?`${pods.length} ${simulated?'demo':'loaded'} pods`:'Configured · not in loaded pods'}</small></button>})}</div><p>Grafana has Loki and Tempo data sources configured. Alertmanager is configured in the monitoring chart. Exporter containers are not independent machines.</p><p>node-exporter and kube-state-metrics appear only if present in loaded workload names:</p>{residents.filter(p=>/node-exporter|kube-state-metrics/.test(p.workload.name)).map(p=><button key={p.name} onClick={()=>onHighlight(p.workload.name)}>{p.workload.name}</button>)}</>:<><p className="topology-source">Loaded Service selector matches · not verified endpoint membership or packet traffic</p>{services.length?services.map(service=><section key={service}><h3>{service}</h3>{residents.filter(p=>p.services.includes(service)).map(p=><button className="topology-service-path" key={`${p.workload.namespace}/${p.name}`} onClick={()=>onHighlight(p.workload.name)}><span>{p.name}</span><small>→ {p.node||'Unscheduled'} · {p.workload.namespace}</small></button>)}</section>):<p>No matched Services in this selection.</p>}<p>Service → EndpointSlice → pod is the routing relationship. This map currently has selector matches; the aggregate readiness probe checks EndpointSlices separately.</p></>}
 {facility==='control'&&<section className="configured-subnets" aria-label="Configured subnet layout"><h3>Terraform subnet plan</h3><p>Configured boundaries—not live node placement.</p><div className="subnet-zones">{['AZ 1','AZ 2','AZ 3'].map(zone=><div key={zone}><strong>{zone}</strong><span>Public</span><span>Private workers</span><span>Intra interfaces</span></div>)}</div></section>}
 <a href={facility==='control'?'#/summary':facility==='services'?'#/network':'#/observability'}>Open full inspection</a></aside>
}
